### ISSUE TITLE
Notification publisher configuration cannot be read after upgrade from 3.8.0 to 4.1.0

### ISSUE THREAD

**Issue by dfn-certling** [DependencyTrack/v3.8.0-v4.0.0-migration#9]
### Current Behavior:
After migrating from 3.8.0 to 4.1.0 the notification publisher configuration in `NOTIFICATIONRULE.PUBLISHER_CONFIG` cannot be read by the application (at least for the email publisher). In 3.8.0 this is stored as a large object in the database while 4.1.0 stores it directly in the column. Other large objects like license texts or vulnerability descriptions work.

### Steps to Reproduce:
1. Setup a database and configure an email notification with destination address with 3.8.0
2. Run the migration script
3. Run the 4.1.0 API server

### Expected Behavior:
I expect the configuration to be read and visible in the frontend.

### Environment:
  
  - Dependency-Track Version: 4.1.0
  - Distribution: Executable WAR
  - BOM Format & Version:
  - Database Server: PostgreSQL
  - Browser: Firefox

**Comment by dfn-certling** [comment]
This does not seem to be related to the migration. I just tried with the docker images against a PostgreSQL container. Using the docker-compose.yml from the project for 3.8.0 and 4.x (4.0.0, 4.0.1, and 4.1.0) with an additional PostgreSQL, I just started the containers, logged in and created an email notification with some email address. Under 3.8.0 the configuration is stored as a large object, under 4.x it is stored directly in NOTIFICATIONRULE.

The compose files are modified to use the following PostgreSQL configuration and container:
```yaml
# dependency-track environment
- ALPINE_DATABASE_MODE=external
- ALPINE_DATABASE_URL=jdbc:postgresql://postgres:5432/dtrack
- ALPINE_DATABASE_DRIVER=org.postgresql.Driver
- ALPINE_DATABASE_DRIVER_PATH=/extlib/postgresql-42.2.18.jar
- ALPINE_DATABASE_USERNAME=dtrack
- ALPINE_DATABASE_PASSWORD=dtrack

# PostgreSQL container
  postgres10:
    image: postgres:10
    environment:
      POSTGRES_USER: dtrack
      POSTGRES_PASSWORD: dtrack
```

The NOTIFICATIONRULEs in the PostgreSQL container look like this in 3.8.0
```sql
dtrack=# select * from "NOTIFICATIONRULE";
 ID | ENABLED | MESSAGE | NAME | NOTIFICATION_LEVEL | NOTIFY_ON | PUBLISHER | PUBLISHER_CONFIG |   SCOPE   |                 UUID
----+---------+---------+------+--------------------+-----------+-----------+------------------+-----------+--------------------------------------
  1 | t       |         | test | INFORMATIONAL      |           |         3 | 21637            | PORTFOLIO | 07b7d3ff-81e4-4eec-bec3-5964df7cd9b4
(1 row)

dtrack=# select convert_from(lo_get(21637), 'UTF8');
      convert_from
------------------------
 {"destination":"test"}
(1 row)
```

and like this in 4.x
```sql
dtrack=# select * from "NOTIFICATIONRULE";
 ID | ENABLED | MESSAGE | NAME | NOTIFICATION_LEVEL | NOTIFY_ON | PUBLISHER |    PUBLISHER_CONFIG    |   SCOPE   |                 UUID
----+---------+---------+------+--------------------+-----------+-----------+------------------------+-----------+--------------------------------------
  1 | t       |         | test | INFORMATIONAL      |           |         3 | {"destination":"test"} | PORTFOLIO | d8bcd674-ac0c-4f20-b7cd-a33129fa0559
(1 row)
```
